language: cpp
compiler:
  - gcc

env:
  matrix:
    - NODE_NVM_VERSION="0.10"
    - NODE_NVM_VERSION="0.8"

before_install:
  - sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -y
  - sudo apt-get install -y pkg-config make gcc-4.8 g++-4.8
  - sudo ./test/build-static.sh
  - git clone https://github.com/creationix/nvm.git ../.nvm
  - source ../.nvm/nvm.sh
  - nvm install $NODE_NVM_VERSION
  - nvm use $NODE_NVM_VERSION
  - node --version
  - npm --version
  - npm install mocha
